CREATE TABLE share_images (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  hash CHAR(8) NOT NULL,
  summary VARCHAR(255) NOT NULL,
  location VARCHAR(255) DEFAULT '',
  start_date INT UNSIGNED NOT NULL,
  end_date INT UNSIGNED NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY (hash)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
