CREATE TABLE `template_backgrounds` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `filename` varchar(255) NOT NULL,
  `original_name` varchar(255) NOT NULL,
  `width` int unsigned NOT NULL DEFAULT '0',
  `height` int unsigned NOT NULL DEFAULT '0',
  `is_active` tinyint(1) NOT NULL DEFAULT '1',
  `text_offset` int NOT NULL DEFAULT '0',
  `summary_margin_top` int NOT NULL DEFAULT '180',
  `summary_font_size` int unsigned NOT NULL DEFAULT '36',
  `date_font_size` int unsigned NOT NULL DEFAULT '24',
  `date_margin_top` int NOT NULL DEFAULT '25',
  `time_font_size` int unsigned NOT NULL DEFAULT '36',
  `time_margin_top` int NOT NULL DEFAULT '25',
  `location_font_size` int unsigned NOT NULL DEFAULT '24',
  `location_margin_top` int NOT NULL DEFAULT '25',
  `font_color` varchar(7) NOT NULL DEFAULT '#ffffff',
  `glow_radius` int unsigned NOT NULL DEFAULT '0',
  `glow_color` varchar(7) NOT NULL DEFAULT '#ffffff',
  `shadow_offset` int unsigned NOT NULL DEFAULT '0',
  `stroke_width` int unsigned NOT NULL DEFAULT '0',
  `stroke_color` varchar(7) NOT NULL DEFAULT '#000000',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

CREATE TABLE `template_photos` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `filename` varchar(255) NOT NULL,
  `original_name` varchar(255) NOT NULL,
  `width` int unsigned NOT NULL DEFAULT '0',
  `height` int unsigned NOT NULL DEFAULT '0',
  `is_active` tinyint(1) NOT NULL DEFAULT '1',
  `photo_x` int NOT NULL DEFAULT '0',
  `photo_y` int NOT NULL DEFAULT '0',
  `photo_scale` int unsigned NOT NULL DEFAULT '100',
  `photo_glow_radius` int unsigned NOT NULL DEFAULT '0',
  `photo_glow_color` varchar(7) NOT NULL DEFAULT '#000000',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

CREATE TABLE `templates` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `background_id` int unsigned NOT NULL,
  `photo_id` int unsigned NOT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT '1',
  `photo_x` int NOT NULL DEFAULT '0',
  `photo_y` int NOT NULL DEFAULT '0',
  `photo_scale` int unsigned NOT NULL DEFAULT '100',
  `photo_glow_radius` int unsigned NOT NULL DEFAULT '0',
  `photo_glow_color` varchar(7) NOT NULL DEFAULT '#000000',
  `text_offset` int NOT NULL DEFAULT '0',
  `summary_margin_top` int NOT NULL DEFAULT '180',
  `summary_font_size` int unsigned NOT NULL DEFAULT '36',
  `date_font_size` int unsigned NOT NULL DEFAULT '24',
  `date_margin_top` int NOT NULL DEFAULT '25',
  `time_font_size` int unsigned NOT NULL DEFAULT '36',
  `time_margin_top` int NOT NULL DEFAULT '25',
  `location_font_size` int unsigned NOT NULL DEFAULT '24',
  `location_margin_top` int NOT NULL DEFAULT '25',
  `font_color` varchar(7) NOT NULL DEFAULT '#ffffff',
  `glow_radius` int unsigned NOT NULL DEFAULT '0',
  `glow_color` varchar(7) NOT NULL DEFAULT '#ffffff',
  `shadow_offset` int unsigned NOT NULL DEFAULT '0',
  `stroke_width` int unsigned NOT NULL DEFAULT '0',
  `stroke_color` varchar(7) NOT NULL DEFAULT '#000000',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_bg_photo` (`background_id`,`photo_id`),
  KEY `photo_id` (`photo_id`),
  FOREIGN KEY (`background_id`) REFERENCES `template_backgrounds` (`id`) ON DELETE CASCADE,
  FOREIGN KEY (`photo_id`) REFERENCES `template_photos` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
